manifest:
  remotes:

    - name: West Update
      run: |
        rm -rf modules/prospector-zmk-module zephyr modules .west build
        west update -f --clean --reset-modules
        west list prospector-zmk-module   # ← 確認用

    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: rschenk
      url-base: https://github.com/rschenk
    - name: prospector
#      url-base: https://github.com/t-ogura
      url-base: https://github.com/Kijitora114514

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # Raytac MDBT50Q
    - name: zmk-component-raytac-dongle
      remote: rschenk
      revision: v0.4

    # Prospector dongle module (display and adapter)
    - name: prospector-zmk-module
      remote: prospector
      revision: 1b889f8c152ad849bcab19a399dd42e44c8aafd5
      path: modules/prospector-zmk-module

  self:
    path: config
